version: "3.9"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://127.0.0.1:27017/mytaskdb
    depends_on:
      - mongo
    networks:
        - app_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
        - app_network

  mongo:
      image: mongo
      ports:
        - "27017:27017"
      networks:
         - app_network

networks:
    app_network:
